package wurmatron.voidrpg.api.materials;

public enum MaterialType {
		ALL, // All Parts
		HELMET, FACE_GUARD, HELMET_ARMOR, HELMET_ALL, // HELMET
		LEFT_ARM, RIGHT_ARM, ARMS, INNER_CHEST, ARMOR_CHEST, CHEST, LEFT_HAND, RIGHT_HAND, HAND, // CHESTPLATE
		TOP_LEFT_LEGGING, TOP_RIGHT_LEGGING, TOP_LEGGING, BOTTOM_LEFT_LEGGING, BOTTOM_RIGHT_LEGGING, BOTTOM_LEGGING, LEGGING, // LEGGINGS
		LEFT_BOOT, RIGHT_BOOT, ARMOR_LEFT_BOOT, ARMOR_RIGHT_BOOT, BOOT // BOOTS
}
